"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Clock3, Crown, Mail, MessageCircle } from "lucide-react";
import { useState } from "react";
import { Dialog, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ESEWA_ACCOUNT, ESEWA_QR_SRC, PRO_PLANS, SUPPORT_PHONE, SUPPORT_WHATSAPP_URL } from "@/lib/pro-plan";
import { cn } from "@/lib/utils";

export function PaymentActivationModal({ onSignup }: { onSignup?: () => void }) {
  const [open, setOpen] = useState(true);
  const [step, setStep] = useState(0);
  const [selectedPlan, setSelectedPlan] = useState<(typeof PRO_PLANS)[number]["id"]>("monthly");
  const plan = PRO_PLANS.find((item) => item.id === selectedPlan) ?? PRO_PLANS[0];
  return <Dialog open={open} onOpenChange={setOpen} className="!max-w-lg sm:p-7">
    <DialogHeader className="pr-7"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#B8F34A] text-[#041A15]"><Crown className="h-6 w-6" /></div><DialogTitle className="mt-2 text-center text-xl text-[#123F37]">Activate FitNMove Pro</DialogTitle><DialogDescription className="text-center">A quick three-step guide to complete your activation.</DialogDescription></DialogHeader>
    <div className="mt-5 flex items-center gap-2">{["Plan", "Pay", "Confirm"].map((label, index) => <div key={label} className="flex min-w-0 flex-1 items-center gap-2"><span className={cn("flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-black", index <= step ? "bg-[#123F37] text-white" : "bg-[#EAF8F4] text-[#6B7773]")}>{index < step ? <Check className="h-4 w-4" /> : index + 1}</span><span className={cn("hidden truncate text-xs font-bold sm:block", index <= step ? "text-[#123F37]" : "text-[#6B7773]")}>{label}</span>{index < 2 && <span className={cn("h-px flex-1", index < step ? "bg-[#123F37]" : "bg-[#DCE7DC")} />}</div>)}</div>
    {step === 0 && <div key="plan" className="mt-6 space-y-4 animate-modal-in"><div className="relative overflow-hidden rounded-2xl bg-[#0B2C24] p-4 text-white"><video className="absolute inset-0 h-full w-full object-cover opacity-35" autoPlay muted loop playsInline preload="metadata" src="/Workout/workoutclips/Fullbody/jumpingjacks.mp4" /><div className="relative"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#B8F34A]">Step 1 · Your plan</p><h3 className="mt-1 text-xl font-black">Choose your Pro level</h3><p className="mt-1 text-sm leading-5 text-white/75">One payment unlocks the full FitNMove experience.</p></div></div><div className="space-y-2">{PRO_PLANS.map((item) => <button type="button" key={item.id} onClick={() => setSelectedPlan(item.id)} className={cn("flex w-full items-center justify-between rounded-2xl border p-4 text-left transition-all duration-300", selectedPlan === item.id ? "border-[#20C7A4] bg-[#EAF8F4] shadow-[0_8px_24px_rgba(32,199,164,0.18)]" : "border-[#E3EAE7] hover:-translate-y-0.5 hover:border-[#20C7A4]/60")}><span><span className="block text-sm font-black text-[#17201E]">{item.name}</span><span className="mt-1 block text-xs text-[#6B7773]">{item.note}</span></span><span className="shrink-0 text-lg font-black text-[#123F37]">{item.price}</span></button>)}</div><button type="button" onClick={() => onSignup?.() ?? setStep(1)} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#123F37] px-4 text-sm font-bold text-white shadow-lg shadow-[#123F37]/20 transition-all hover:-translate-y-0.5 hover:bg-[#15483F]">{onSignup ? "Sign up to activate Pro" : "Continue to payment"} <ArrowRight className="h-4 w-4" /></button></div>}
    {step === 1 && <div key="pay" className="mt-6 space-y-4 animate-modal-in"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-[#20C7A4]">Step 2 · Payment</p><h3 className="mt-1 text-lg font-black text-[#17201E]">Pay {plan.price}</h3><p className="mt-1 text-sm leading-5 text-[#6B7773]">Scan this eSewa QR or send the exact amount to the account below.</p></div><div className="overflow-hidden rounded-2xl border border-[#20C7A4]/30 bg-gradient-to-br from-[#EAF8F4] to-white p-3 shadow-inner"><Image src={ESEWA_QR_SRC} alt="eSewa payment QR code" width={420} height={420} className="mx-auto aspect-square w-full max-w-[230px] rounded-xl object-contain transition-transform duration-500 hover:scale-[1.03]" /></div><div className="rounded-2xl bg-[#EAF8F4] p-4"><p className="text-xs font-bold uppercase text-[#6B7773]">eSewa account</p><p className="mt-1 text-2xl font-black tabular-nums text-[#123F37]">{ESEWA_ACCOUNT}</p><p className="mt-1 text-xs font-semibold text-[#6B7773]">Amount to pay: {plan.price}</p></div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setStep(0)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#DCE7DC] text-sm font-bold text-[#123F37]"><ArrowLeft className="h-4 w-4" /> Back</button><button type="button" onClick={() => setStep(2)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#123F37] text-sm font-bold text-white transition-all hover:-translate-y-0.5">I have paid <ArrowRight className="h-4 w-4" /></button></div></div>}
    {step === 2 && <div key="confirm" className="mt-6 space-y-4 animate-modal-in"><div className="relative overflow-hidden rounded-2xl bg-[#0B2C24] p-4 text-white"><Image src="/images/hubpage.png" alt="FitNMove app preview" width={900} height={520} className="absolute inset-0 h-full w-full object-cover opacity-25" /><div className="relative"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#B8F34A]">Step 3 · Almost there</p><h3 className="mt-1 text-xl font-black">Send payment details</h3><p className="mt-1 text-sm leading-5 text-white/80">Your account will be activated within 24 hours after verification.</p></div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-3 text-amber-900"><Clock3 className="mt-0.5 h-5 w-5 shrink-0" /><p className="text-sm leading-6">Send your eSewa transaction ID and payment screenshot. Include the email you used to sign up and the selected plan ({plan.price}).</p></div></div><div className="space-y-2"><a href={SUPPORT_WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#25D366] px-4 text-sm font-black text-white shadow-lg shadow-[#25D366]/20 transition-all hover:-translate-y-0.5 hover:bg-[#1FBA59]"><MessageCircle className="h-5 w-5" /> WhatsApp assistance · {SUPPORT_PHONE}</a><a href="mailto:fitnmovenp@gmail.com" className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-[#DCE7DC] bg-white px-4 text-sm font-bold text-[#123F37] hover:bg-[#F7FAF9]"><Mail className="h-4 w-4" /> Mail assistance · fitnmovenp@gmail.com</a></div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setStep(1)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#DCE7DC] text-sm font-bold text-[#123F37]"><ArrowLeft className="h-4 w-4" /> Back</button><Link href="/demo" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#123F37] text-sm font-bold text-white">Try limited demo</Link></div></div>}
  </Dialog>;
}
