"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { ArrowLeft, Clock3, ImagePlus, Loader2, Pencil, Plus, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc-client";

type Exercise = { label: string; exercise: string; clipSrc: string; sets: number; reps: number; seconds: number; restSeconds: number; tracking: "manual" | "timer" };
type ProgramForm = { id?: string; slug: string; name: string; tagline: string; difficulty: "Beginner" | "Intermediate" | "Advanced"; durationMin: number; goal: string; equipment: string; muscles: string; calories: number; bannerImage: string; pointsReward: number; tags: string; isPublished: boolean; sortOrder: number; exercises: Exercise[] };
const blankExercise = (): Exercise => ({ label: "", exercise: "", clipSrc: "", sets: 1, reps: 10, seconds: 0, restSeconds: 20, tracking: "manual" });
const blankProgram = (): ProgramForm => ({ slug: "", name: "", tagline: "", difficulty: "Beginner", durationMin: 10, goal: "Strength", equipment: "No Equipment", muscles: "", calories: 0, bannerImage: "", pointsReward: 100, tags: "", isPublished: true, sortOrder: 0, exercises: [blankExercise()] });
const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

export function WorkoutProgramAdmin() {
  const utils = trpc.useUtils();
  const { data: programs = [], isLoading, error } = trpc.workoutPrograms.listAdmin.useQuery(undefined, { retry: false });
  const [form, setForm] = useState<ProgramForm | null>(null);
  const [uploading, setUploading] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const refresh = () => Promise.all([utils.workoutPrograms.listAdmin.invalidate(), utils.workoutPrograms.listPublished.invalidate()]);
  const create = trpc.workoutPrograms.create.useMutation({ onSuccess: () => { void refresh(); setForm(null); toast.success("Program created."); }, onError: (item) => toast.error(item.message) });
  const update = trpc.workoutPrograms.update.useMutation({ onSuccess: () => { void refresh(); setForm(null); toast.success("Program updated."); }, onError: (item) => toast.error(item.message) });
  const remove = trpc.workoutPrograms.delete.useMutation({ onSuccess: () => { void refresh(); toast.success("Program deleted."); }, onError: (item) => toast.error(item.message) });
  const saving = create.isPending || update.isPending;

  const edit = (program: typeof programs[number]) => setForm({ id: program.programId, slug: program.slug, name: program.name, tagline: program.tagline, difficulty: program.difficulty as ProgramForm["difficulty"], durationMin: program.durationMin, goal: program.goal, equipment: program.equipment, muscles: program.muscles.join(", "), calories: program.calories, bannerImage: program.bannerImage ?? "", pointsReward: program.pointsReward, tags: program.tags.join(", "), isPublished: program.isPublished, sortOrder: program.sortOrder, exercises: program.exercises.map((item) => ({ label: item.label, exercise: item.exercise ?? "", clipSrc: item.clipSrc ?? "", sets: item.sets, reps: item.reps ?? 0, seconds: item.seconds ?? 0, restSeconds: item.restSeconds ?? 0, tracking: item.tracking })) });
  const updateExercise = (index: number, change: Partial<Exercise>) => setForm((current) => current ? { ...current, exercises: current.exercises.map((item, itemIndex) => itemIndex === index ? { ...item, ...change } : item) } : current);
  const submit = () => {
    if (!form) return;
    const payload = { ...form, muscles: split(form.muscles), tags: split(form.tags), bannerImage: form.bannerImage || null, exercises: form.exercises.map(({ exercise, clipSrc, reps, seconds, ...item }) => ({ ...item, ...(exercise ? { exercise } : {}), ...(clipSrc ? { clipSrc } : {}), ...(item.tracking === "timer" ? { seconds } : { reps }) })) };
    if (form.id) update.mutate({ ...payload, id: form.id }); else create.mutate(payload);
  };
  const uploadBanner = async (file?: File) => {
    if (!file) return;
    setUploading(true);
    try {
      const body = new FormData(); body.set("file", file); body.set("folder", "progress-photos");
      const response = await fetch("/api/upload", { method: "POST", body });
      const result = await response.json() as { url?: string; error?: string };
      if (!response.ok || !result.url) throw new Error(result.error || "Upload failed.");
      setForm((current) => current ? { ...current, bannerImage: result.url! } : current);
    } catch (uploadError) { toast.error(uploadError instanceof Error ? uploadError.message : "Upload failed."); } finally { setUploading(false); }
  };
  if (error) return <main className="mx-auto max-w-2xl px-4 py-10"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-[#15483F]"><ArrowLeft className="h-4 w-4" /> Back to admin</Link><section className="mt-5 rounded-3xl border border-amber-300 bg-amber-50 p-6"><h1 className="text-xl font-black text-[#17201E]">Workout programs need setup</h1><p className="mt-2 text-sm text-amber-950">Run the supplied Supabase SQL migration, then refresh this page.</p></section></main>;

  return <main className="mx-auto max-w-6xl px-4 py-5 pb-28 sm:px-6 sm:py-8">
    <header className="rounded-[28px] bg-[#10372D] px-5 py-6 text-white shadow-sm sm:px-7 sm:py-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-[#B8F34A]"><ArrowLeft className="h-4 w-4" /> Admin dashboard</Link><h1 className="mt-3 text-2xl font-black sm:text-3xl">Workout programs</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#C0D1CA]">Build guided routines with a banner, exercise targets, timers, and breaks.</p></div><Button onClick={() => setForm(blankProgram())} className="min-h-11 shrink-0 rounded-full bg-[#B8F34A] px-5 font-black text-[#10372D] hover:bg-[#D1FF77]"><Plus className="h-4 w-4" /> New program</Button></div></header>
    <section className="mt-5"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-black text-[#17201E]">Your programs</h2><p className="text-sm text-[#6B7773]">{programs.length} total</p></div></div>{isLoading ? <div className="flex min-h-48 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#15483F]" /></div> : programs.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{programs.map((program) => <article key={program.programId} className="overflow-hidden rounded-[24px] border border-[#DDE8E4] bg-white shadow-sm"><div className="relative h-36 bg-[#EAF8F4]">{program.bannerImage ? <img src={program.bannerImage} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-sm font-black text-[#15483F]">FitNMove program</div>}<span className={`absolute left-3 top-3 rounded-full px-2.5 py-1 text-[11px] font-black ${program.isPublished ? "bg-[#B8F34A] text-[#10372D]" : "bg-white text-[#6B7773]"}`}>{program.isPublished ? "Published" : "Draft"}</span></div><div className="p-4"><div className="flex gap-3"><div className="min-w-0 flex-1"><h3 className="truncate font-black text-[#17201E]">{program.name}</h3><p className="mt-1 line-clamp-2 text-sm leading-5 text-[#6B7773]">{program.tagline}</p></div><span className="inline-flex h-9 shrink-0 items-center gap-1 rounded-full bg-[#F1F6F4] px-3 text-xs font-black text-[#15483F]"><Clock3 className="h-3.5 w-3.5" />{program.durationMin}m</span></div><p className="mt-4 text-xs font-bold text-[#6B7773]">{program.exercises.length} exercises · {program.goal}</p><div className="mt-4 flex gap-2"><Button variant="outline" className="min-h-10 flex-1 rounded-xl" onClick={() => edit(program)}><Pencil className="h-4 w-4" /> Edit</Button><Button variant="outline" size="icon" className="h-10 w-10 rounded-xl text-red-600" onClick={() => { if (window.confirm(`Delete ${program.name}?`)) remove.mutate({ id: program.programId }); }}><Trash2 className="h-4 w-4" /></Button></div></div></article>)}</div> : <div className="rounded-3xl border border-dashed border-[#B8D8CE] bg-[#F7FAF9] px-6 py-14 text-center"><h3 className="font-black text-[#17201E]">No programs yet</h3><p className="mt-2 text-sm text-[#6B7773]">Create your first guided workout program.</p><Button className="mt-5 rounded-full" onClick={() => setForm(blankProgram())}><Plus className="h-4 w-4" /> Create program</Button></div>}</section>
    {form && <div className="fixed inset-0 z-[70] overflow-y-auto bg-black/45 p-0 sm:p-5"><section className="ml-auto min-h-full w-full max-w-3xl bg-white p-4 shadow-2xl sm:min-h-0 sm:rounded-[28px] sm:p-6"><div className="sticky top-0 z-10 -mx-4 flex items-center justify-between border-b border-[#DDE8E4] bg-white px-4 pb-4 sm:-mx-6 sm:px-6"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-[#20C7A4]">Program editor</p><h2 className="mt-1 text-xl font-black text-[#17201E]">{form.id ? "Edit program" : "Create program"}</h2></div><Button variant="outline" className="rounded-full" onClick={() => setForm(null)}>Close</Button></div>
      <div className="space-y-6 pt-5"><section className="grid gap-3 sm:grid-cols-2"><Field label="Program name"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Full Body Strength" /></Field><Field label="Program slug"><Input value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value.toLowerCase().replace(/\s+/g, "-") })} placeholder="full-body-strength" /></Field><Field label="Description" wide><Input value={form.tagline} onChange={(event) => setForm({ ...form, tagline: event.target.value })} placeholder="A short description for users" /></Field><Field label="Goal"><Input value={form.goal} onChange={(event) => setForm({ ...form, goal: event.target.value })} /></Field><Field label="Equipment"><Input value={form.equipment} onChange={(event) => setForm({ ...form, equipment: event.target.value })} /></Field><Field label="Focus muscles"><Input value={form.muscles} onChange={(event) => setForm({ ...form, muscles: event.target.value })} placeholder="Chest, Triceps" /></Field><Field label="Tags"><Input value={form.tags} onChange={(event) => setForm({ ...form, tags: event.target.value })} placeholder="Strength, Beginner" /></Field><Field label="Duration (minutes)"><Input type="number" min="1" value={form.durationMin} onChange={(event) => setForm({ ...form, durationMin: Number(event.target.value) })} /></Field><Field label="Estimated calories"><Input type="number" min="0" value={form.calories} onChange={(event) => setForm({ ...form, calories: Number(event.target.value) })} /></Field><Field label="Difficulty"><select value={form.difficulty} onChange={(event) => setForm({ ...form, difficulty: event.target.value as ProgramForm["difficulty"] })} className="h-10 w-full rounded-md border border-input bg-white px-3 text-sm"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></Field><label className="flex min-h-10 items-center gap-2 self-end rounded-xl bg-[#F1F6F4] px-3 text-sm font-bold text-[#15483F]"><input type="checkbox" checked={form.isPublished} onChange={(event) => setForm({ ...form, isPublished: event.target.checked })} className="accent-[#15483F]" /> Publish for users</label></section>
        <section className="rounded-2xl border border-[#DDE8E4] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-[#17201E]">Banner image</h3><p className="mt-1 text-xs text-[#6B7773]">Upload an image or use a public image URL.</p></div><Button type="button" variant="outline" className="rounded-full" onClick={() => fileRef.current?.click()} disabled={uploading}>{uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />} Upload</Button><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/heic" className="hidden" onChange={(event) => void uploadBanner(event.target.files?.[0])} /></div><div className="mt-3 flex flex-col gap-3 sm:flex-row"><div className="flex h-24 w-full shrink-0 items-center justify-center overflow-hidden rounded-xl bg-[#F1F6F4] sm:w-40">{form.bannerImage ? <img src={form.bannerImage} alt="Banner preview" className="h-full w-full object-cover" /> : <ImagePlus className="h-6 w-6 text-[#6B7773]" />}</div><Input value={form.bannerImage} onChange={(event) => setForm({ ...form, bannerImage: event.target.value })} placeholder="https://..." /></div></section>
        <section><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-[#17201E]">Exercises</h3><p className="mt-1 text-xs text-[#6B7773]">Set reps or a timed hold, then the break after that exercise.</p></div><Button type="button" variant="outline" className="rounded-full" onClick={() => setForm({ ...form, exercises: [...form.exercises, blankExercise()] })}><Plus className="h-4 w-4" /> Add exercise</Button></div><div className="mt-3 space-y-3">{form.exercises.map((exercise, index) => <article key={index} className="rounded-2xl border border-[#DDE8E4] bg-[#F9FCFB] p-3 sm:p-4"><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-[#15483F] px-2.5 py-1 text-xs font-black text-white">Exercise {index + 1}</span><Button type="button" variant="ghost" size="sm" disabled={form.exercises.length === 1} className="text-red-600" onClick={() => setForm({ ...form, exercises: form.exercises.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 className="h-4 w-4" /> Remove</Button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Input value={exercise.label} onChange={(event) => updateExercise(index, { label: event.target.value })} placeholder="Exercise name" /><Input value={exercise.exercise} onChange={(event) => updateExercise(index, { exercise: event.target.value })} placeholder="Exercise key (optional)" /><Input value={exercise.clipSrc} onChange={(event) => updateExercise(index, { clipSrc: event.target.value })} placeholder="Clip path (optional)" /><Field label="Sets"><Input type="number" min="1" value={exercise.sets} onChange={(event) => updateExercise(index, { sets: Number(event.target.value) })} /></Field><Field label={exercise.tracking === "timer" ? "Hold seconds" : "Reps"}><Input type="number" min="1" value={exercise.tracking === "timer" ? exercise.seconds : exercise.reps} onChange={(event) => updateExercise(index, exercise.tracking === "timer" ? { seconds: Number(event.target.value) } : { reps: Number(event.target.value) })} /></Field><Field label="Break seconds"><Input type="number" min="0" value={exercise.restSeconds} onChange={(event) => updateExercise(index, { restSeconds: Number(event.target.value) })} /></Field><Field label="Target type"><select value={exercise.tracking} onChange={(event) => updateExercise(index, { tracking: event.target.value as Exercise["tracking"] })} className="h-10 w-full rounded-md border border-input bg-white px-3 text-sm"><option value="manual">Reps</option><option value="timer">Timed hold</option></select></Field></div></article>)}</div></section>
        <Button className="min-h-12 w-full rounded-full bg-[#15483F] font-black" disabled={saving} onClick={submit}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : null}{form.id ? "Save changes" : "Create program"}</Button>
      </div></section></div>}
  </main>;
}

function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) {
  return <label className={`grid gap-1.5 text-xs font-bold text-[#45615A] ${wide ? "sm:col-span-2" : ""}`}><span>{label}</span>{children}</label>;
}
